#!/usr/bin/env node
const config = require("../languages/language-configuration");
const fs = require("fs");
fs.writeFileSync(
  "./languages/language-configuration.json",
  JSON.stringify(config, null, 2),
  "utf8"
);
